"""event table

Revision ID: 27a4bb9bc050
Revises: aa9533c86b96
Create Date: 2021-07-05 14:40:19.648159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a4bb9bc050'
down_revision = 'aa9533c86b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('datetime', sa.DateTime(timezone=120), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('unique_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['unique_id'], ['chronicle.unique_id'], ),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_index(op.f('ix_event_datetime'), 'event', ['datetime'], unique=False)
    op.drop_index('ix_chronicle_max_timestamp', table_name='chronicle')
    op.create_index(op.f('ix_chronicle_max_timestamp'), 'chronicle', ['max_timestamp'], unique=False)
    op.drop_index('ix_chronicle_min_timestamp', table_name='chronicle')
    op.create_index(op.f('ix_chronicle_min_timestamp'), 'chronicle', ['min_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chronicle_min_timestamp'), table_name='chronicle')
    op.create_index('ix_chronicle_min_timestamp', 'chronicle', ['min_timestamp'], unique=False)
    op.drop_index(op.f('ix_chronicle_max_timestamp'), table_name='chronicle')
    op.create_index('ix_chronicle_max_timestamp', 'chronicle', ['max_timestamp'], unique=False)
    op.drop_index(op.f('ix_event_datetime'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
