"""chromicle table

Revision ID: aa9533c86b96
Revises: 
Create Date: 2021-07-05 14:15:17.070827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9533c86b96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chronicle',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('min_timestamp', sa.DateTime(timezone=120), nullable=True),
    sa.Column('max_timestamp', sa.DateTime(timezone=120), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_index(op.f('ix_chronicle_max_timestamp'), 'chronicle', ['max_timestamp'], unique=True)
    op.create_index(op.f('ix_chronicle_min_timestamp'), 'chronicle', ['min_timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chronicle_min_timestamp'), table_name='chronicle')
    op.drop_index(op.f('ix_chronicle_max_timestamp'), table_name='chronicle')
    op.drop_table('chronicle')
    # ### end Alembic commands ###
