"""edit datetime chronicle

Revision ID: ead6a97c55b0
Revises: b9bb80599345
Create Date: 2021-07-05 15:34:01.004466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead6a97c55b0'
down_revision = 'b9bb80599345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chronicle', schema=None) as batch_op:
        batch_op.drop_index('ix_chronicle_max_timestamp')
        batch_op.drop_index('ix_chronicle_min_timestamp')
        batch_op.create_index(batch_op.f('ix_chronicle_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_chronicle_unique_id'), ['unique_id'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aircraft', sa.String(length=64), nullable=True))
        batch_op.drop_constraint('fk_event_source_chronicle', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_event_aircraft_chronicle'), 'chronicle', ['aircraft'], ['source'])
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_event_aircraft_chronicle'), type_='foreignkey')
        batch_op.create_foreign_key('fk_event_source_chronicle', 'chronicle', ['source'], ['source'])
        batch_op.drop_column('aircraft')

    with op.batch_alter_table('chronicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chronicle_unique_id'))
        batch_op.drop_index(batch_op.f('ix_chronicle_source'))
        batch_op.create_index('ix_chronicle_min_timestamp', ['min_timestamp'], unique=False)
        batch_op.create_index('ix_chronicle_max_timestamp', ['max_timestamp'], unique=False)

    # ### end Alembic commands ###
